name: "Automatic Package Publishing"
on:
  push:
    branches:
      - master
      - main

jobs:
  publish-package:
    # if: ${{ github.event.pull_request.merged }}
    name: Publish package to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: "emmsdan"
      - uses: technote-space/get-diff-action@v6
        if: env.GIT_DIFF
      - uses: volta-cli/action@v4
      - run: git config --global user.email "stax-bot@staxpayments.com"
      - run: git config --global user.name "Stax Bot"

      - name: Update package version
        run: |
              npm show @emmsdan/github-actions-test version
              npm version patch
              echo "${{ github.ref }}"
              # npm version --new-version "$GITHUB_REF:11"
              npm install
              npm run prepare
      - name: Publish package to internal registry on GitHub
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTION_TOKEN }}
