# This workflow warns that have had no activity for a specified amount of time on a PR
name: "Mark pull requests stale"

on:
  schedule:
    - cron: '* * * * *'
  pull_request_target:
    types: [assigned, opened]

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.ACTION_TOKEN }}
          stale-pr-message: 'No activity on this PR for 30 days. This PR will be closed in 60 days, if no activity (ie comment, issue, commit etc) occurs.'
          stale-pr-label: 'stale'
          days-before-stale: 0.1
          days-before-close: -1
          exempt-pr-labels: 'feature,WIP,question,in-progress, DO NOT MERGE️'
