name: "Build and Run Test cases PR"
on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  run-app-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - name: "Configure '.npmrc'."
        run: |
          echo "@fattmerchantorg:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.STAX_BOT_TOKEN }}" >> ~/.npmrc
          echo "@fortawesome:registry=https://npm.fontawesome.com/" >> ~/.npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONT_AWESOME_TOKEN }}" >> ~/.npmrc
          
      - name: Install dependencies
        run: npm install

      - name: Run tests
      - run: npm run test

      - name: Test complete
        run: echo "Tests complete"

      - name: Run Build
        run: npm run build

      - name: Build complete
        run: echo "Build was successful"
